apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2020-02-01T21:32:16Z'
  labels:
    app.kubernetes.io/instance: guestbook
  name: guestbook-ui
  namespace: guestbook
  selfLink: /apis/route.openshift.io/v1/namespaces/guestbook/routes/guestbook-ui
spec:
  host: guestbook-ui-guestbook.apps.mycluster.demovfernandezg.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: guestbook-ui
    weight: 100
  wildcardPolicy: None
